version: 2.1

orbs:
  python: circleci/python@0.2.1
  postgres: onehq/postgres@1.1.0

jobs:
  build-and-test:
    executor: python/default
    steps:
      - postgres/install_postgres_client
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m unittest test.test_example
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
