version: 2.1

orbs:
  python: circleci/python@0.2.1
  postgres-rspec: sbc-orbs/postgres-rspec@0.0.28

jobs:
  install-db:
    executor:
      name: postgres-rspec/default
      python-version: '3.6.2-stretch-browsers'
    steps:
      - postgres-rspec/install
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m unittest test.test_example
          name: Test

workflows:
  main:
    jobs:
      - install-db
      - build-and-test
