version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    docker:
      - image: circleci/postgres:9.6.20
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: code_eval
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-deps
      - run:
          command: python -m unittest test.test_example
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
